function [coordinate_system_string] = mslGaleMosaic_v3_get_coordinate_system_string()


standard_parallel   = 0;
longitude_of_origin = 0;
rMars               = 3396190.0;
projcs_name = sprintf('Mars Sphere-Based Equirectangular lat%05.2fN',...
    standard_parallel);

spheroid_name       = 'Mars_Sphere';
spheroid_major_axis = rMars;
datum_name  = ['D_' spheroid_name];
geogcs_name = ['GCS_' spheroid_name];

coordinate_system_string = sprintf([                                    ...
    '{PROJCS["%s",GEOGCS["%s",DATUM["%s",SPHEROID["%s",%.15f,0.0]],'        , ...
    'PRIMEM["Reference_Meridian",0.0],UNIT["Degree",0.0174532925199433]],'  , ...
    'PROJECTION["Equidistant_Cylindrical"],PARAMETER["False_Easting",0.0],' , ...
    'PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",%.15f],'  , ...
    'PARAMETER["Standard_Parallel_1",%.15f],'                               , ...
    'UNIT["Meter",1.0]]}']                                                  , ...
    projcs_name,geogcs_name,datum_name,spheroid_name,spheroid_major_axis    , ...
    longitude_of_origin,standard_parallel);

end